FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build -- --configuration production

FROM nginx:1.25-alpine

COPY --from=build /usr/src/app/dist/frontend-angular/browser /usr/share/nginx/html

EXPOSE 80
