services:
  backend:
    container_name: backend_uni_course_finder
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - core_network
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${ISSUER_URI}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=${JWK_SET_URI}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_BACKEND_SERVICE_SECRET=${KEYCLOAK_BACKEND_SERVICE_SECRET}
    labels:
      - traefik.enable=true
      - traefik.docker.network=core_network
      # Path-based routing
      - traefik.http.routers.uni-course-finder-backend.rule=Host(`omeucurso.pt`) && PathPrefix(`/api`)
      - traefik.http.routers.uni-course-finder-backend.entrypoints=websecure
      - traefik.http.routers.uni-course-finder-backend.tls.certresolver=le
      - traefik.http.services.uni-course-finder-backend.loadbalancer.server.port=8080
      - traefik.http.routers.uni-course-finder-backend.middlewares=api-stripper

  frontend:
    container_name: frontend_uni_course_finder
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - core_network
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=core_network
      # Path-based routing
      - traefik.http.routers.uni-course-finder-frontend.rule=Host(`omeucurso.pt`)
      - traefik.http.routers.uni-course-finder-frontend.entrypoints=websecure
      - traefik.http.routers.uni-course-finder-frontend.tls.certresolver=le
      - traefik.http.services.uni-course-finder-frontend.loadbalancer.server.port=80
      # Redirect
      - traefik.http.middlewares.www-to-non-www.redirectregex.regex=^https://www.omeucurso.pt/(.*)
      - traefik.http.middlewares.www-to-non-www.redirectregex.replacement=https://omeucurso.pt/$${1}
      - traefik.http.middlewares.www-to-non-www.redirectregex.permanent=true
      # Router www
      - traefik.http.routers.uni-course-finder-www.rule=Host(`www.uni-course-finder.pt`)
      - traefik.http.routers.uni-course-finder-www.entrypoints=websecure
      - traefik.http.routers.uni-course-finder-www.tls.certresolver=le
      - traefik.http.routers.uni-course-finder-www.middlewares=www-to-non-www
      - traefik.http.routers.uni-course-finder-www.service=omeucurso-frontend

networks:
  core_network:
    external: true