# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/uni_data
spring.datasource.username=postgres
spring.datasource.password=superuser
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Origin configuration
frontend.origin=http://localhost:4200