spring.application.name=Uni Course Finder Backend

# Spring configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.default-schema=public

# CORS
frontend.origin=${FRONTEND_ORIGIN}

# Keycloak
keycloak.backend.service.secret=${KEYCLOAK_BACKEND_SERVICE_SECRET}
keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}