name: Deploy in production

concurrency: production

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'        
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/apps/unicoursefinder
            git pull origin main
            docker compose -f compose.prod.yaml build --no-cache
            docker compose -f compose.prod.yaml down -v
            docker compose -f compose.prod.yaml up -d
            docker image prune -f
